from enum import Enum

class StatusCode(Enum):
    RUNTIME_ERROR = 3
    ACCEPTED = 4
    WRONG_ANSWER = 5
    TIME_LIMIT_EXCEEDED = 6
    MEMORY_LIMIT_EXCEEDED = 7
    OUTPUT_LIMIT_EXCEEDED = 8
    RESTRICTED_CALL = 9
